$(function () {
    var header = '';
    header += '<header id="header" class="fixed-top d-flex align-items-center">';
    header += '<div class="container d-flex align-items-center">';

    header += '<div class="logo me-auto">';
    header += '<a href="index.html"><img src="assets/img/logo.png" alt="Logo de GreenTwins" class="img-fluid"></a>';
    header += '</div>';

    header += '<nav id="navbar" class="navbar order-last order-lg-0">';
    header += '<ul>';
    header += '<li class="dropdown"><a href="#"><span>Produits</span> <i class="bi bi-chevron-down"></i></a>';
    header += '<ul>';
    header += '<li><a class="nav-link scrollto" href="#">Dashboard & suivi de consommation</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Audit énergétique</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Bilan carbone</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Cartographie d\'énergie</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Subvention</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Financement des travaux</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Digitalisation</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Data & IA</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">ISO 51001</a></li>';
    header += '</ul>';
    header += '</li>';
    header += '<li class="dropdown"><a href="#"><span>Technologies</span> <i class="bi bi-chevron-down"></i></a>';
    header += '<ul>';
    header += '<li><a class="nav-link scrollto" href="#">Énergie Management</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Smart Grid Management</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Collecte & valorisation Data</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Digitalisation</a></li>';
    header += '</ul>';
    header += '</li>';
    header += '<li class="dropdown"><a href="#"><span>Métier</span> <i class="bi bi-chevron-down"></i></a>';
    header += '<ul>';
    header += '<li><a class="nav-link scrollto" href="#">Énergie Management</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Smart Grid Management</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Collecte & valorisation Data</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Digitalisation</a></li>';
    header += '</ul>';
    header += '</li>';
    header += '<li class="dropdown"><a href="#"><span>Médias</span> <i class="bi bi-chevron-down"></i></a>';
    header += '<ul>';
    header += '<li><a class="nav-link scrollto" href="#">Blog</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Webinaire</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Vidéo</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Article</a></li>';
    header += '</ul>';
    header += '</li>';
    header += '<li class="dropdown"><a href="#"><span>Contact</span> <i class="bi bi-chevron-down"></i></a>';
    header += '<ul>';
    header += '<li><a class="nav-link scrollto" href="#">@Télévision</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Facebook</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Twitter</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">LinkedIn</a></li>';
    header += '</ul>';
    header += '</li>';
    header += '<li class="dropdown"><a href="#"><span>Espace client</span> <i class="bi bi-chevron-down"></i></a>';
    header += '<ul>';
    header += '<li><a class="nav-link scrollto" href="#">Industriel</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Bureau d\'études</a></li>';
    header += '<li><a class="nav-link scrollto" href="#">Collectivité</a></li>';
    header += '</ul>';
    header += '</li>';
    header += '</ul>';
    header += '<i class="bi bi-list mobile-nav-toggle"></i>';
    header += '</nav>';

    header += '</div>';
    header += '</div>';
    header += '</header>';

    $("#nav_bar_info").html(header);
});
